image: node:20-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - cd server
    - npm install

test:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    MONGODB_URI: "mongodb://mongo:27017/whyTestDB"
  script:
    - cd server
    - MJ_APIKEY_PUBLIC=$MJ_APIKEY_PUBLIC MJ_APIKEY_PRIVATE=$MJ_APIKEY_PRIVATE npm run ci-test
